#!/bin/sh

echo "
USE rightalertdb
GO
INSERT INTO powerdata (\"Bus Voltage\",\"Shunt Voltage\",\"Load Voltage\",\"Current\",\"Watts\")
VALUES ('$1','$2','$3','$4','$5')
GO
exit
" > tempfile

TDSVER=7.0 tsql -H 52.86.93.112 -p 1433 -U rightalert -P savingL1v3s < tempfile

exit